branches:
  only:
    - staging
    - master
    - trying

language: rust
rust: nightly

script:
- cargo check

script:
  - gem install asciidoctor
  - asciidoctor README.adoc -o _html/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DOCS_TOKEN
  keep-history: true
  local-dir: _html
  on:
    branch: master
